# This file was generated by GoReleaser. DO NOT EDIT.
cask "craft-cli" do
  name "craft-cli"
  desc "A CLI tool for Huma Craft Cloud platform"
  homepage "https://github.com/huma-engineering/craft-cloud"
  version "0.1.0-rc.9"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "craft-cli"

  on_macos do
    on_intel do
      url "https://github.com/huma-engineering/craft-cloud/releases/download/v#{version}/craft-cli_#{version}_darwin_amd64.tar.gz"
      sha256 "3b137b5cf7ad0318d2307c8c53d15c2eadccd1b91b3d2797148e3c51d577e3e0"
    end
    on_arm do
      url "https://github.com/huma-engineering/craft-cloud/releases/download/v#{version}/craft-cli_#{version}_darwin_arm64.tar.gz"
      sha256 "a10f5f271de11290ff71c26403a595550ebf138ea7e1bb96e740c425b5e59433"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/huma-engineering/craft-cloud/releases/download/v#{version}/craft-cli_#{version}_linux_amd64.tar.gz"
      sha256 "dc15b11c09358c32c83d5c1f16e58aa59320e3ccdd27700da88c9827154a315a"
    end
    on_arm do
      url "https://github.com/huma-engineering/craft-cloud/releases/download/v#{version}/craft-cli_#{version}_linux_arm64.tar.gz"
      sha256 "70cd774c51c60e878d4917babc4828aa50726acd868964a0a1dd2d1c904573ef"
    end
  end

  # No zap stanza required
end
