# This file was generated by GoReleaser. DO NOT EDIT.
cask "craft-cli" do
  name "craft-cli"
  desc "A CLI tool for Huma Craft Cloud platform"
  homepage "https://github.com/huma-engineering/craft-cloud"
  version "0.2.4"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "craft-cli"
  bash_completion "completions/craft-cli.bash"
  zsh_completion "completions/_craft-cli"
  fish_completion "completions/craft-cli.fish"

  on_macos do
    on_intel do
      url "https://github.com/huma-engineering/homebrew-tap/releases/download/v#{version}/craft-cli_#{version}_darwin_amd64.tar.gz"
      sha256 "031863d4a50d30e0b184a6cbd025899c8423767be3ce5126432dcc5a8fe375d7"
    end
    on_arm do
      url "https://github.com/huma-engineering/homebrew-tap/releases/download/v#{version}/craft-cli_#{version}_darwin_arm64.tar.gz"
      sha256 "79ad84f7f5f830745b16d1bdccc61f2c79404c5ce71567dee9a175c6e8af5635"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/huma-engineering/homebrew-tap/releases/download/v#{version}/craft-cli_#{version}_linux_amd64.tar.gz"
      sha256 "58b02f06b97e6a6f036220180eb7d187f860f56a4d7c590ccc76da7c9abdc077"
    end
    on_arm do
      url "https://github.com/huma-engineering/homebrew-tap/releases/download/v#{version}/craft-cli_#{version}_linux_arm64.tar.gz"
      sha256 "c45a0fb1b8b48f474a4fd107aa65234d565258e8637dabd90e6483425c12db93"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/craft-cli"]
    end
    system_command "#{staged_path}/craft-cli", args: ["version"], print_stdout: true
  end

  # No zap stanza required
end
