# This file was generated by GoReleaser. DO NOT EDIT.
cask "craft-cli" do
  name "craft-cli"
  desc "A CLI tool for Huma Craft Cloud platform"
  homepage "https://github.com/huma-engineering/craft-cloud"
  version "0.1.0-rc.13"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "craft-cli"
  bash_completion "completions/craft-cli.bash"
  zsh_completion "completions/_craft-cli"
  fish_completion "completions/craft-cli.fish"

  on_macos do
    on_intel do
      url "https://github.com/huma-engineering/homebrew-craft-cli/releases/download/v#{version}/craft-cli_#{version}_darwin_amd64.tar.gz"
      sha256 "ce4ee11d3cdf1894233920332c696f04a4ae1959209848fa01d43ceb29227e9b"
    end
    on_arm do
      url "https://github.com/huma-engineering/homebrew-craft-cli/releases/download/v#{version}/craft-cli_#{version}_darwin_arm64.tar.gz"
      sha256 "34d68714a7f8d2fb3b55ae87718fe6790e53ad84acbc09eb659a0bd7019f11e3"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/huma-engineering/homebrew-craft-cli/releases/download/v#{version}/craft-cli_#{version}_linux_amd64.tar.gz"
      sha256 "895b309746d42914b957b5c179e0431ce0db56c7f6f91a67707af09eb07d24be"
    end
    on_arm do
      url "https://github.com/huma-engineering/homebrew-craft-cli/releases/download/v#{version}/craft-cli_#{version}_linux_arm64.tar.gz"
      sha256 "07d86523a26dd2bf1a276ee305141af1d29014d53c209db4e0d557ba0992dc47"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/craft-cli"]
    end
    system_command "#{staged_path}/craft-cli", args: ["version"]
  end

  # No zap stanza required
end
